package com.desafioitau.api.transferencia.repository.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "tb_comprovante")
public class ComprovanteEntity implements Serializable {


    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String idCliente;

    @DynamoDBAttribute
    private Date dataHoraComprovante;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedJson(targetType = ContaTransacaoEntity.class)
    private ContaTransacaoEntity conta;


}
